[tool.poetry]
name = "pythonproject3"
version = "0.1.0"
description = ""
authors = ["imbon <i.m.bondarev@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
pytest = "^8.4.2"
txt = "^2020.11.12"
flake8 = "==6.0.0"
coverage = "==7.3.2"
pytest-cov = "==4.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
